Для решения задач нам понадобится выделить из признака title год выпуска фильма. Для этого напишем функцию get_year_release(arg).

In [3]:
import pandas as pd

ratings_movies = pd.read_csv('data/ratings_movies.csv')
ratings_movies.head()

,Unnamed: 0,userId,movieId,rating,date,title,genres
0,0,1,1,4.0,2000-07-30 18:45:03,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,1,1,3,4.0,2000-07-30 18:20:47,Grumpier Old Men (1995),Comedy|Romance
2,2,1,6,4.0,2000-07-30 18:37:04,Heat (1995),Action|Crime|Thriller
3,3,1,47,5.0,2000-07-30 19:03:35,Seven (a.k.a. Se7en) (1995),Mystery|Thriller
4,4,1,50,5.0,2000-07-30 18:48:51,"Usual Suspects, The (1995)",Crime|Mystery|Thriller

In [8]:
#библиотека для регулярных выражений
import re 
def get_year_release(arg):
    #находим все слова по шаблону "(DDDD)"
    candidates = re.findall(r'\(\d{4}\)', arg) 
    # проверяем число вхождений
    if len(candidates) > 0:
        #если число вхождений больше 0,
	#очищаем строку от знаков "(" и ")"
        year = candidates[0].replace('(', '')
        year = year.replace(')', '')
        return int(year)
    else:
        #если год не указан, возвращаем None
        return None

Данная функция основана на регулярных выражениях и использует модуль re, с которым мы пока не работали.

→ Модуль re предназначен для поиска шаблонов в тексте и встроен в язык, поэтому не нуждается в установке.

Из модуля re нам понадобится только функция findall(), которая позволяет найти в строке все слова, удовлетворяющие шаблону. Мы находим в строке с названием фильма шаблон "(DDDD)" — четыре цифры, обёрнутых в скобки, что соответствует году выпуска фильма. Если такого шаблона не было найдено (год выпуска не указан), функция возвращает None (в таблице это будет помечено как пропуск).

## Задачи

Задание 1

Создайте в таблице новый признак year_release, который соответствует году выпуска фильма.\
У скольких фильмов не указан год их выпуска?

In [5]:

# Извлекаем год выпуска из названия фильма
ratings_movies['year_release'] = ratings_movies['title'].str.extract(r'\((\d{4})\)').astype(float)

# Считаем количество фильмов, у которых год выпуска отсутствует
missing_year_count = ratings_movies['year_release'].isna().sum()

# Выводим таблицу и результат
print(ratings_movies)
print(f"Количество фильмов без указанного года выпуска: {missing_year_count}")

        Unnamed: 0  userId  movieId  rating                 date  \
0                0       1        1     4.0  2000-07-30 18:45:03
1                1       1        3     4.0  2000-07-30 18:20:47
2                2       1        6     4.0  2000-07-30 18:37:04
3                3       1       47     5.0  2000-07-30 19:03:35
4                4       1       50     5.0  2000-07-30 18:48:51
...            ...     ...      ...     ...                  ...
100831      100831     610   166534     4.0  2017-05-03 21:53:22
100832      100832     610   168248     5.0  2017-05-03 22:21:31
100833      100833     610   168250     5.0  2017-05-08 19:50:47
100834      100834     610   168252     5.0  2017-05-03 21:19:12
100835      100835     610   170875     3.0  2017-05-03 21:20:15

                                 title  \
0                     Toy Story (1995)
1              Grumpier Old Men (1995)
2                          Heat (1995)
3          Seven (a.k.a. Se7en) (1995)
4           Usual Suspects, The (1995)
...                                ...
100831                    Split (2017)
100832   John Wick: Chapter Two (2017)
100833                  Get Out (2017)
100834                    Logan (2017)
100835  The Fate of the Furious (2017)

                                             genres  year_release
0       Adventure|Animation|Children|Comedy|Fantasy        1995.0
1                                    Comedy|Romance        1995.0
2                             Action|Crime|Thriller        1995.0
3                                  Mystery|Thriller        1995.0
4                            Crime|Mystery|Thriller        1995.0
...                                             ...           ...
100831                        Drama|Horror|Thriller        2017.0
100832                        Action|Crime|Thriller        2017.0
100833                                       Horror        2017.0
100834                                Action|Sci-Fi        2017.0
100835                  Action|Crime|Drama|Thriller        2017.0

[100836 rows x 8 columns]
Количество фильмов без указанного года выпуска: 18

Задание 2

Какой фильм, выпущенный в 1999 году, получил наименьшую среднюю оценку зрителей?\
В качестве ответа запишите название этого фильма без указания года его выпуска.

In [11]:
# Извлекаем год выпуска из названия фильма
ratings_movies['year'] = ratings_movies['title'].str.extract(r'\((\d{4})\)')

# Преобразуем год в числовой формат, игнорируя ошибки
ratings_movies['year'] = pd.to_numeric(ratings_movies['year'], errors='coerce')

# Фильтруем фильмы, выпущенные в 1999 году
movies_1999 = ratings_movies[ratings_movies['year'] == 1999]

# Вычисляем средние оценки для каждого фильма
average_ratings = movies_1999.groupby('title')['rating'].mean().reset_index()

# Находим фильм с наименьшей средней оценкой
lowest_rated_movie = average_ratings.loc[average_ratings['rating'].idxmin()]

# Вывод результата
print(f"Фильм с наименьшей средней оценкой: {lowest_rated_movie['title']}")

Фильм с наименьшей средней оценкой: Bloodsport: The Dark Kumite (1999)

In [12]:
# Если нужно узнать количество фильмов без года:
# Перед фильтрацией можно посчитать строки, где year равен NaN:


missing_years_count = ratings_movies['year'].isna().sum()
print(f"Количество фильмов без указания года выпуска: {missing_years_count}")

Количество фильмов без указания года выпуска: 18

Задание 3

Какое сочетание жанров фильмов (genres), выпущенных в 2010 году, получило наименьшую среднюю оценку (rating)?\
Запишите сочетание так же, как оно указано в таблице (через разделитель |, без пробелов).

In [48]:
# Фильтруем данные по году выпуска (2010)
movies_2010 = ratings_movies[ratings_movies['year'] == 2010]

# Группируем по жанрам и вычисляем средний рейтинг
average_ratings_genres = movies_2010.groupby('genres')['rating'].mean().reset_index()

# Сортируем по возрастанию среднего рейтинга
sorted_ratings = average_ratings_genres.sort_values(by='rating')

# Находим жанр с наименьшей средней оценкой
lowest_rated_genres = sorted_ratings.iloc[0]

# Выводим результат
print(f"Сочетание жанров с наименьшей средней оценкой: {lowest_rated_genres['genres']}")

Сочетание жанров с наименьшей средней оценкой: Неизвестно

Задание 4

Какой пользователь (userId) посмотрел наибольшее количество различных (уникальных) комбинаций жанров (genres) фильмов? В качестве ответа запишите\ идентификатор этого пользователя.

In [56]:
# Создаем столбец с уникальной комбинацией жанров для каждого фильма
ratings_movies['genre_combination'] = ratings_movies['genres'].apply(lambda x: tuple(sorted(x.split('|'))))

# Сгруппируем по пользователям и посчитаем количество уникальных комбинаций жанров
unique_genre_combinations_per_user = ratings_movies.groupby('userId')['genre_combination'].nunique()

# Сортируем по убыванию
sorted_unique_genre_combinations = unique_genre_combinations_per_user.sort_values(ascending=False)

# Индекс первой строки будет пользователем с наибольшим количеством уникальных жанров
user_with_most_genre_combinations = sorted_unique_genre_combinations.idxmax()

# Выводим результат
print(f"Пользователь с наибольшим количеством уникальных жанров: {user_with_most_genre_combinations}")

Пользователь с наибольшим количеством уникальных жанров: 610

Задание 5

Найдите пользователя, который выставил наименьшее количество оценок, но его средняя оценка фильмам наибольшая.\
В качестве ответа укажите идентификатор этого пользователя.\
Чтобы рассчитать несколько параметров для каждого пользователя (количество оценок и среднюю оценку), можно воспользоваться методом agg() на сгруппированных данных.

In [57]:
# Группируем данные по userId и рассчитываем количество оценок и среднюю оценку
user_stats = ratings_movies.groupby('userId').agg(
    count_ratings=('rating', 'count'),
    avg_rating=('rating', 'mean')
).reset_index()

# Сортируем по средней оценке (по убыванию) и по количеству оценок (по возрастанию)
sorted_user_stats = user_stats.sort_values(by=['avg_rating', 'count_ratings'], ascending=[False, True])

# Извлекаем пользователя с наибольшей средней оценкой и наименьшим количеством оценок
user_with_best_rating = sorted_user_stats.iloc[0]

# Выводим идентификатор этого пользователя
print(user_with_best_rating['userId'])

53.0

адание 6

Найдите сочетание жанров (genres) за 2018 год, которое имеет наибольший средний рейтинг (среднее по столбцу rating), и при этом число выставленных ему оценок (количество значений в столбце rating) больше 10.\
Запишите сочетание так же, как оно указано в таблице (через разделитель |, без пробелов).

In [59]:
# Фильтруем данные по году выпуска 2018
movies_2018 = ratings_movies[ratings_movies['year'] == 2018]

# Группируем по жанрам и рассчитываем средний рейтинг и количество оценок
genre_stats = movies_2018.groupby('genres').agg(
    avg_rating=('rating', 'mean'),
    count_ratings=('rating', 'count')
).reset_index()

# Фильтруем сочетания жанров с количеством оценок больше 10
genre_stats_filtered = genre_stats[genre_stats['count_ratings'] > 10]

# Сортируем по среднему рейтингу по убыванию
genre_stats_sorted = genre_stats_filtered.sort_values(by='avg_rating', ascending=False)

# Индекс первой строки будет содержать сочетание жанров с наибольшим рейтингом
best_genre_combination = genre_stats_sorted.iloc[0]['genres']

# Выводим результат
print(best_genre_combination)

Неизвестно

Задание 8.7

Добавьте в таблицу новый признак year_rating — год выставления оценки. Создайте сводную таблицу, которая иллюстрирует зависимость среднего рейтинга фильма от года выставления оценки и жанра.

In [64]:
import pandas as pd

# Загружаем данные
ratings_movies = pd.read_csv('data/ratings_movies.csv')

# Преобразуем столбец 'date' в формат datetime и извлекаем год
ratings_movies['year_rating'] = pd.to_datetime(ratings_movies['date']).dt.year

# Создаем сводную таблицу с зависимостью среднего рейтинга от года и жанра
pivot_table = ratings_movies.pivot_table(
    values='rating', 
    index='year_rating', 
    columns='genres', 
    aggfunc='mean', 
    fill_value=0
)

# Выводим сводную таблицу
print(pivot_table)

genres       (no genres listed)    Action  Action|Adventure  \
year_rating
1996                   0.000000  2.730769          3.454545
1997                   0.000000  3.538462          4.150000
1998                   0.000000  0.000000          4.200000
1999                   0.000000  0.000000          4.000000
2000                   0.000000  2.588235          3.738462
2001                   0.000000  3.000000          3.500000
2002                   0.000000  2.750000          4.304348
2003                   0.000000  3.833333          3.277778
2004                   0.000000  2.700000          4.136364
2005                   0.000000  3.357143          3.413043
2006                   0.000000  2.166667          4.090909
2007                   0.000000  2.583333          3.666667
2008                   0.000000  3.000000          3.656250
2009                   0.000000  0.000000          3.714286
2010                   0.000000  3.500000          3.437500
2011                   0.000000  4.500000          3.888889
2012                   0.000000  2.625000          3.900000
2013                   0.000000  2.500000          3.833333
2014                   0.000000  0.000000          3.875000
2015                   0.500000  3.100000          3.560976
2016                   3.500000  3.545455          3.722222
2017                   3.000000  2.637931          3.527778
2018                   3.676471  2.588235          3.397436

genres       Action|Adventure|Animation  Action|Adventure|Animation|Children  \
year_rating
1996                              0.000                             0.000000
1997                              0.000                             0.000000
1998                              0.000                             0.000000
1999                              0.000                             0.000000
2000                              0.000                             0.000000
2001                              0.000                             0.000000
2002                              0.000                             0.000000
2003                              0.000                             0.000000
2004                              0.000                             0.000000
2005                              0.000                             0.000000
2006                              0.000                             0.000000
2007                              0.000                             0.000000
2008                              0.000                             0.000000
2009                              0.000                             0.000000
2010                              0.000                             0.000000
2011                              0.000                             0.000000
2012                              0.000                             4.000000
2013                              0.000                             3.000000
2014                              3.000                             3.500000
2015                              3.800                             3.666667
2016                              3.750                             3.833333
2017                              3.375                             3.500000
2018                              3.650                             3.166667

genres       Action|Adventure|Animation|Children|Comedy  \
year_rating
1996                                           0.000000
1997                                           0.000000
1998                                           0.000000
1999                                           0.000000
2000                                           0.000000
2001                                           0.000000
2002                                           0.000000
2003                                           0.000000
2004                                           4.000000
2005                                           4.107143
2006                                           3.833333
2007                                           3.846154
2008                                           4.125000
2009                                           3.900000
2010                                           4.333333
2011                                           3.500000
2012                                           3.785714
2013                                           4.333333
2014                                           3.250000
2015                                           3.565217
2016                                           3.925000
2017                                           3.676471
2018                                           3.741935

genres       Action|Adventure|Animation|Children|Comedy|Fantasy  \
year_rating
1996                                                  0.000000
1997                                                  0.000000
1998                                                  0.000000
1999                                                  0.000000
2000                                                  0.000000
2001                                                  0.000000
2002                                                  0.000000
2003                                                  0.000000
2004                                                  0.000000
2005                                                  0.000000
2006                                                  0.000000
2007                                                  3.000000
2008                                                  4.000000
2009                                                  0.000000
2010                                                  0.000000
2011                                                  0.000000
2012                                                  0.000000
2013                                                  0.000000
2014                                                  3.833333
2015                                                  3.833333
2016                                                  3.388889
2017                                                  3.700000
2018                                                  4.142857

genres       Action|Adventure|Animation|Children|Comedy|IMAX  \
year_rating
1996                                                0.000000
1997                                                0.000000
1998                                                0.000000
1999                                                0.000000
2000                                                0.000000
2001                                                0.000000
2002                                                0.000000
2003                                                0.000000
2004                                                0.000000
2005                                                0.000000
2006                                                0.000000
2007                                                0.000000
2008                                                0.000000
2009                                                3.250000
2010                                                3.500000
2011                                                0.000000
2012                                                3.550000
2013                                                5.000000
2014                                                3.500000
2015                                                3.375000
2016                                                3.666667
2017                                                1.000000
2018                                                3.700000

genres       Action|Adventure|Animation|Children|Comedy|Romance  \
year_rating
1996                                                  0.000000
1997                                                  0.000000
1998                                                  0.000000
1999                                                  0.000000
2000                                                  0.000000
2001                                                  0.000000
2002                                                  0.000000
2003                                                  0.000000
2004                                                  0.000000
2005                                                  0.000000
2006                                                  0.000000
2007                                                  0.000000
2008                                                  0.000000
2009                                                  0.000000
2010                                                  3.000000
2011                                                  0.000000
2012                                                  4.000000
2013                                                  0.000000
2014                                                  4.000000
2015                                                  2.333333
2016                                                  1.000000
2017                                                  1.000000
2018                                                  2.500000

genres       Action|Adventure|Animation|Children|Comedy|Sci-Fi  ...  \
year_rating                                                     ...
1996                                                       0.0  ...
1997                                                       0.0  ...
1998                                                       0.0  ...
1999                                                       0.0  ...
2000                                                       0.0  ...
2001                                                       0.0  ...
2002                                                       0.0  ...
2003                                                       0.0  ...
2004                                                       0.0  ...
2005                                                       0.0  ...
2006                                                       3.0  ...
2007                                                       2.8  ...
2008                                                       3.5  ...
2009                                                       2.5  ...
2010                                                       0.0  ...
2011                                                       4.0  ...
2012                                                       0.0  ...
2013                                                       0.0  ...
2014                                                       0.0  ...
2015                                                       2.5  ...
2016                                                       4.0  ...
2017                                                       2.0  ...
2018                                                       4.0  ...

genres       Romance|Thriller  Romance|War  Romance|Western    Sci-Fi  \
year_rating
1996                    0.000          0.0              0.0  0.000000
1997                    0.000          0.0              0.0  0.000000
1998                    0.000          0.0              0.0  0.000000
1999                    2.000          0.0              0.0  0.000000
2000                    4.000          0.0              3.0  3.416667
2001                    0.000          0.0              3.0  2.500000
2002                    3.000          0.0              0.0  3.750000
2003                    3.375          2.5              0.0  2.333333
2004                    3.000          3.0              3.5  2.125000
2005                    2.000          0.0              0.0  3.000000
2006                    0.000          0.0              0.0  0.500000
2007                    1.500          0.0              2.5  3.375000
2008                    0.000          0.0              0.0  3.125000
2009                    0.000          0.0              0.0  2.000000
2010                    0.000          0.0              0.0  4.000000
2011                    0.000          0.0              0.0  3.500000
2012                    2.500          0.0              0.0  4.166667
2013                    0.000          0.0              0.0  1.500000
2014                    0.000          0.0              0.0  2.500000
2015                    0.000          0.0              0.0  2.900000
2016                    2.500          0.0              0.0  3.555556
2017                    3.000          0.0              0.0  3.864865
2018                    0.000          0.0              0.0  3.128571

genres       Sci-Fi|IMAX  Sci-Fi|Thriller  Sci-Fi|Thriller|IMAX  Thriller  \
year_rating
1996            0.000000         2.666667              0.000000  3.838095
1997            0.000000         3.400000              0.000000  3.923077
1998            0.000000         0.000000              0.000000  3.800000
1999            0.000000         4.000000              0.000000  3.700000
2000            0.000000         2.142857              0.000000  3.087912
2001            0.000000         2.500000              0.000000  3.477273
2002            0.000000         3.600000              0.000000  3.583333
2003            0.000000         3.142857              0.000000  3.250000
2004            0.000000         0.000000              0.000000  3.464286
2005            0.000000         2.750000              0.000000  3.411765
2006            0.000000         4.500000              0.000000  3.735294
2007            0.000000         2.833333              0.000000  3.421875
2008            0.000000         3.000000              0.000000  3.333333
2009            0.000000         4.000000              0.000000  2.964286
2010            0.000000         2.500000              0.000000  2.833333
2011            0.000000         1.833333              4.000000  3.625000
2012            0.000000         3.500000              3.666667  3.083333
2013            0.000000         3.833333              4.000000  3.666667
2014            5.000000         0.000000              4.000000  4.000000
2015            4.071429         3.764706              4.000000  2.911765
2016            3.807692         3.916667              3.666667  3.432432
2017            4.264706         3.750000              2.500000  3.152174
2018            3.500000         3.562500              0.000000  3.296296

genres       War   Western
year_rating
1996         0.0  3.117647
1997         0.0  3.000000
1998         0.0  0.000000
1999         4.5  4.000000
2000         3.0  4.058824
2001         3.0  3.111111
2002         3.5  3.000000
2003         3.0  4.000000
2004         3.0  3.800000
2005         0.0  4.500000
2006         0.0  3.625000
2007         0.0  3.000000
2008         0.0  4.000000
2009         4.0  3.375000
2010         0.0  3.666667
2011         0.0  4.000000
2012         0.0  4.100000
2013         0.0  4.000000
2014         0.0  4.000000
2015         0.0  3.900000
2016         0.0  3.958333
2017         0.0  2.933333
2018         0.0  3.611111

[23 rows x 951 columns]

In [65]:
# Проверка A: Минимальная оценка для сочетания Action|Adventure
action_adventure = pivot_table['Action|Adventure']
min_action_adventure = action_adventure.min()

# Проверка B: Средний рейтинг для сочетания Action|Adventure|Animation|Children|Comedy|IMAX в 2010 году
rating_2010 = pivot_table.loc[2010, 'Action|Adventure|Animation|Children|Comedy|IMAX']

# Проверка C: Наивысшие средние оценки для 2018 года
rating_2018 = pivot_table.loc[2018]
max_rating_2018 = rating_2018.max()
genres_max_rating_2018 = rating_2018[rating_2018 == max_rating_2018].index.tolist()

# Проверка D: Тренд изменения среднего рейтинга для жанра Comedy
comedy_rating_trend = pivot_table['Comedy']

# Вывод результатов
(min_action_adventure, rating_2010, genres_max_rating_2018, comedy_rating_trend)

(np.float64(3.2777777777777777),
 np.float64(3.5),
 ['Action|Comedy|Documentary',
  'Action|Crime|Sci-Fi|Thriller',
  'Action|Crime|Thriller|Western',
  'Adventure|Children|Comedy|Fantasy|Mystery',
  'Adventure|Fantasy|Musical',
  'Animation|Children|Mystery',
  'Animation|Comedy|Drama',
  'Animation|Comedy|Drama|Fantasy|Sci-Fi',
  'Animation|Comedy|Fantasy|Musical',
  'Animation|Crime|Drama',
  'Comedy|Crime|Fantasy',
  'Comedy|Crime|Horror|Thriller',
  'Comedy|Drama|Fantasy|Mystery|Romance',
  'Comedy|Fantasy|Horror|Musical|Thriller',
  'Comedy|Horror|Mystery',
  'Crime|Fantasy|Horror',
  'Crime|Mystery',
  'Drama|Horror|Mystery|Sci-Fi|Thriller',
  'Drama|Romance|War',
  'Mystery|Romance|Sci-Fi|Thriller',
  'Romance|Sci-Fi'],
 year_rating
 1996    3.228571
 1997    3.409091
 1998    3.000000
 1999    3.606061
 2000    3.141291
 2001    3.318408
 2002    3.198556
 2003    3.120066
 2004    3.356877
 2005    2.963325
 2006    3.347534
 2007    2.928187
 2008    3.426667
 2009    3.273292
 2010    3.179825
 2011    3.232877
 2012    3.478477
 2013    3.489474
 2014    3.271429
 2015    3.106183
 2016    3.373431
 2017    2.852668
 2018    3.121296
 Name: Comedy, dtype: float64)

In [66]:
# Переводим столбец 'date' в формат datetime
ratings_movies['date'] = pd.to_datetime(ratings_movies['date'])

# Извлекаем год из столбца 'date' и создаем новый столбец 'year_rating'
ratings_movies['year_rating'] = ratings_movies['date'].dt.year

# Создаем сводную таблицу: годы (year_rating), жанры (genres), средняя оценка (rating)
pivot_table = pd.pivot_table(ratings_movies, 
                             values='rating', 
                             index='year_rating', 
                             columns='genres', 
                             aggfunc='mean')

# Выводим сводную таблицу
print(pivot_table)

genres       (no genres listed)    Action  Action|Adventure  \
year_rating
1996                        NaN  2.730769          3.454545
1997                        NaN  3.538462          4.150000
1998                        NaN       NaN          4.200000
1999                        NaN       NaN          4.000000
2000                        NaN  2.588235          3.738462
2001                        NaN  3.000000          3.500000
2002                        NaN  2.750000          4.304348
2003                        NaN  3.833333          3.277778
2004                        NaN  2.700000          4.136364
2005                        NaN  3.357143          3.413043
2006                        NaN  2.166667          4.090909
2007                        NaN  2.583333          3.666667
2008                        NaN  3.000000          3.656250
2009                        NaN       NaN          3.714286
2010                        NaN  3.500000          3.437500
2011                        NaN  4.500000          3.888889
2012                        NaN  2.625000          3.900000
2013                        NaN  2.500000          3.833333
2014                        NaN       NaN          3.875000
2015                   0.500000  3.100000          3.560976
2016                   3.500000  3.545455          3.722222
2017                   3.000000  2.637931          3.527778
2018                   3.676471  2.588235          3.397436

genres       Action|Adventure|Animation  Action|Adventure|Animation|Children  \
year_rating
1996                                NaN                                  NaN
1997                                NaN                                  NaN
1998                                NaN                                  NaN
1999                                NaN                                  NaN
2000                                NaN                                  NaN
2001                                NaN                                  NaN
2002                                NaN                                  NaN
2003                                NaN                                  NaN
2004                                NaN                                  NaN
2005                                NaN                                  NaN
2006                                NaN                                  NaN
2007                                NaN                                  NaN
2008                                NaN                                  NaN
2009                                NaN                                  NaN
2010                                NaN                                  NaN
2011                                NaN                                  NaN
2012                                NaN                             4.000000
2013                                NaN                             3.000000
2014                              3.000                             3.500000
2015                              3.800                             3.666667
2016                              3.750                             3.833333
2017                              3.375                             3.500000
2018                              3.650                             3.166667

genres       Action|Adventure|Animation|Children|Comedy  \
year_rating
1996                                                NaN
1997                                                NaN
1998                                                NaN
1999                                                NaN
2000                                                NaN
2001                                                NaN
2002                                                NaN
2003                                                NaN
2004                                           4.000000
2005                                           4.107143
2006                                           3.833333
2007                                           3.846154
2008                                           4.125000
2009                                           3.900000
2010                                           4.333333
2011                                           3.500000
2012                                           3.785714
2013                                           4.333333
2014                                           3.250000
2015                                           3.565217
2016                                           3.925000
2017                                           3.676471
2018                                           3.741935

genres       Action|Adventure|Animation|Children|Comedy|Fantasy  \
year_rating
1996                                                       NaN
1997                                                       NaN
1998                                                       NaN
1999                                                       NaN
2000                                                       NaN
2001                                                       NaN
2002                                                       NaN
2003                                                       NaN
2004                                                       NaN
2005                                                       NaN
2006                                                       NaN
2007                                                  3.000000
2008                                                  4.000000
2009                                                       NaN
2010                                                       NaN
2011                                                       NaN
2012                                                       NaN
2013                                                       NaN
2014                                                  3.833333
2015                                                  3.833333
2016                                                  3.388889
2017                                                  3.700000
2018                                                  4.142857

genres       Action|Adventure|Animation|Children|Comedy|IMAX  \
year_rating
1996                                                     NaN
1997                                                     NaN
1998                                                     NaN
1999                                                     NaN
2000                                                     NaN
2001                                                     NaN
2002                                                     NaN
2003                                                     NaN
2004                                                     NaN
2005                                                     NaN
2006                                                     NaN
2007                                                     NaN
2008                                                     NaN
2009                                                3.250000
2010                                                3.500000
2011                                                     NaN
2012                                                3.550000
2013                                                5.000000
2014                                                3.500000
2015                                                3.375000
2016                                                3.666667
2017                                                1.000000
2018                                                3.700000

genres       Action|Adventure|Animation|Children|Comedy|Romance  \
year_rating
1996                                                       NaN
1997                                                       NaN
1998                                                       NaN
1999                                                       NaN
2000                                                       NaN
2001                                                       NaN
2002                                                       NaN
2003                                                       NaN
2004                                                       NaN
2005                                                       NaN
2006                                                       NaN
2007                                                       NaN
2008                                                       NaN
2009                                                       NaN
2010                                                  3.000000
2011                                                       NaN
2012                                                  4.000000
2013                                                       NaN
2014                                                  4.000000
2015                                                  2.333333
2016                                                  1.000000
2017                                                  1.000000
2018                                                  2.500000

genres       Action|Adventure|Animation|Children|Comedy|Sci-Fi  ...  \
year_rating                                                     ...
1996                                                       NaN  ...
1997                                                       NaN  ...
1998                                                       NaN  ...
1999                                                       NaN  ...
2000                                                       NaN  ...
2001                                                       NaN  ...
2002                                                       NaN  ...
2003                                                       NaN  ...
2004                                                       NaN  ...
2005                                                       NaN  ...
2006                                                       3.0  ...
2007                                                       2.8  ...
2008                                                       3.5  ...
2009                                                       2.5  ...
2010                                                       NaN  ...
2011                                                       4.0  ...
2012                                                       NaN  ...
2013                                                       NaN  ...
2014                                                       NaN  ...
2015                                                       2.5  ...
2016                                                       4.0  ...
2017                                                       2.0  ...
2018                                                       4.0  ...

genres       Romance|Thriller  Romance|War  Romance|Western    Sci-Fi  \
year_rating
1996                      NaN          NaN              NaN       NaN
1997                      NaN          NaN              NaN       NaN
1998                      NaN          NaN              NaN       NaN
1999                    2.000          NaN              NaN       NaN
2000                    4.000          NaN              3.0  3.416667
2001                      NaN          NaN              3.0  2.500000
2002                    3.000          NaN              NaN  3.750000
2003                    3.375          2.5              NaN  2.333333
2004                    3.000          3.0              3.5  2.125000
2005                    2.000          NaN              NaN  3.000000
2006                      NaN          NaN              NaN  0.500000
2007                    1.500          NaN              2.5  3.375000
2008                      NaN          NaN              NaN  3.125000
2009                      NaN          NaN              NaN  2.000000
2010                      NaN          NaN              NaN  4.000000
2011                      NaN          NaN              NaN  3.500000
2012                    2.500          NaN              NaN  4.166667
2013                      NaN          NaN              NaN  1.500000
2014                      NaN          NaN              NaN  2.500000
2015                      NaN          NaN              NaN  2.900000
2016                    2.500          NaN              NaN  3.555556
2017                    3.000          NaN              NaN  3.864865
2018                      NaN          NaN              NaN  3.128571

genres       Sci-Fi|IMAX  Sci-Fi|Thriller  Sci-Fi|Thriller|IMAX  Thriller  \
year_rating
1996                 NaN         2.666667                   NaN  3.838095
1997                 NaN         3.400000                   NaN  3.923077
1998                 NaN              NaN                   NaN  3.800000
1999                 NaN         4.000000                   NaN  3.700000
2000                 NaN         2.142857                   NaN  3.087912
2001                 NaN         2.500000                   NaN  3.477273
2002                 NaN         3.600000                   NaN  3.583333
2003                 NaN         3.142857                   NaN  3.250000
2004                 NaN              NaN                   NaN  3.464286
2005                 NaN         2.750000                   NaN  3.411765
2006                 NaN         4.500000                   NaN  3.735294
2007                 NaN         2.833333                   NaN  3.421875
2008                 NaN         3.000000                   NaN  3.333333
2009                 NaN         4.000000                   NaN  2.964286
2010                 NaN         2.500000                   NaN  2.833333
2011                 NaN         1.833333              4.000000  3.625000
2012                 NaN         3.500000              3.666667  3.083333
2013                 NaN         3.833333              4.000000  3.666667
2014            5.000000              NaN              4.000000  4.000000
2015            4.071429         3.764706              4.000000  2.911765
2016            3.807692         3.916667              3.666667  3.432432
2017            4.264706         3.750000              2.500000  3.152174
2018            3.500000         3.562500                   NaN  3.296296

genres       War   Western
year_rating
1996         NaN  3.117647
1997         NaN  3.000000
1998         NaN       NaN
1999         4.5  4.000000
2000         3.0  4.058824
2001         3.0  3.111111
2002         3.5  3.000000
2003         3.0  4.000000
2004         3.0  3.800000
2005         NaN  4.500000
2006         NaN  3.625000
2007         NaN  3.000000
2008         NaN  4.000000
2009         4.0  3.375000
2010         NaN  3.666667
2011         NaN  4.000000
2012         NaN  4.100000
2013         NaN  4.000000
2014         NaN  4.000000
2015         NaN  3.900000
2016         NaN  3.958333
2017         NaN  2.933333
2018         NaN  3.611111

[23 rows x 951 columns]